pipeline:
  test: 
    image: "python:3.5-slim"
    when:
      event: [push,pull_request]
      branches: "master"
    commands:
      - "sudo apt install wget"
      - "pip3 install tox"
      - "tox -e py35"

